version: "3.8"

services:
  tracardi-api:
    container_name: tracardi-api
    image: tracardi/tracardi-api:0.8.1
    environment:
      ELASTIC_HOST: http://elasticsearch:9200
      REDIS_HOST: redis://redis:6379
      LOGGING_LEVEL: info
      DEMO: 'no'
      PRODUCTION: 'yes'
    ports:
      - 8686:80
    depends_on:
      - elasticsearch
      - redis

  tracardi-gui:
    container_name: tracardi-gui
    image: tracardi/tracardi-gui:0.8.1
    ports:
      - 8787:80
    depends_on:
      - tracardi-api

  tracardi-worker:
    container_name: tracardi-worker
    image: tracardi/update-worker:0.8.1
    environment:
      REDIS_HOST: redis://redis:6379
    depends_on:
      - redis
    
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    environment:
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      xpack.security.enabled: "false"
      cluster.name: contextElasticSearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  redis:
    container_name: redis
    image: redis

networks:
  default:
    name: app
    external: true

volumes:
  elasticsearch_data:
    driver: local
